DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS planet CASCADE;

CREATE TABLE client (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        passport VARCHAR(255)
);

CREATE TABLE planet (
                        id VARCHAR(255) NOT NULL PRIMARY KEY,
                        name VARCHAR(500) NOT NULL,
                        CHECK (id REGEXP  '^[A-Z0-9]+$')
);

CREATE TABLE ticket (
                        ticketId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        createdAt TIMESTAMP WITH TIME ZONE,
                        client_id BIGINT,
                        from_planet_id VARCHAR(255) ,
                        to_planet_id VARCHAR(255) ,
                        CONSTRAINT FK_ticket_client FOREIGN KEY (client_id) REFERENCES client(Id) ON DELETE CASCADE,
                        CONSTRAINT FK_ticket_from_planet FOREIGN KEY (from_planet_id) REFERENCES planet(id) ON DELETE CASCADE,
                        CONSTRAINT FK_ticket_to_planet FOREIGN KEY (to_planet_id) REFERENCES planet(id) ON DELETE CASCADE
);